export * from './accessControlledAction';
export * from './accessControlledResource';
export * from './actionId';
export * from './adjustHolding';
export * from './adjustHoldingRequest';
export * from './aggregateSpec';
export * from './aggregationContext';
export * from './aggregationOptions';
export * from './aggregationRequest';
export * from './aggregationResponseNodeOfDictionaryOfStringToObject';
export * from './analyticStore';
export * from './analyticStoreKey';
export * from './annulQuotesResponse';
export * from './annulStructuredDataResponse';
export * from './change';
export * from './completePortfolio';
export * from './configurationRecipe';
export * from './constituentsAdjustmentHeader';
export * from './corporateAction';
export * from './corporateActionSource';
export * from './corporateActionTransition';
export * from './corporateActionTransitionComponent';
export * from './corporateActionTransitionComponentRequest';
export * from './corporateActionTransitionRequest';
export * from './createAnalyticStoreRequest';
export * from './createCorporateActionSourceRequest';
export * from './createCutLabelDefinitionRequest';
export * from './createDataTypeRequest';
export * from './createDerivedTransactionPortfolioRequest';
export * from './createPortfolioDetails';
export * from './createPortfolioGroupRequest';
export * from './createPropertyDefinitionRequest';
export * from './createReferencePortfolioRequest';
export * from './createResults';
export * from './createTransactionPortfolioRequest';
export * from './createUnitDefinition';
export * from './currencyAndAmount';
export * from './cutLabelDefinition';
export * from './cutLocalTime';
export * from './dataType';
export * from './deleteInstrumentPropertiesResponse';
export * from './deleteInstrumentResponse';
export * from './deletedEntityResponse';
export * from './errorDetail';
export * from './executionRequest';
export * from './expandedGroup';
export * from './fieldSchema';
export * from './fileResponse';
export * from './getInstrumentsResponse';
export * from './getQuotesResponse';
export * from './getReferencePortfolioConstituentsResponse';
export * from './getStructuredMarketDataResponse';
export * from './holdingAdjustment';
export * from './holdingsAdjustment';
export * from './holdingsAdjustmentHeader';
export * from './iUnitDefinitionDto';
export * from './idSelectorDefinition';
export * from './identifierPartSchema';
export * from './instrument';
export * from './instrumentAnalytic';
export * from './instrumentDefinition';
export * from './instrumentEconomicDefinition';
export * from './instrumentIdTypeDescriptor';
export * from './instrumentIdValue';
export * from './instrumentMatch';
export * from './instrumentSearchProperty';
export * from './link';
export * from './listAggregationResponse';
export * from './lusidProblemDetails';
export * from './lusidValidationProblemDetails';
export * from './marketContext';
export * from './marketContextSuppliers';
export * from './marketDataKeyRule';
export * from './marketOptions';
export * from './metricValue';
export * from './modelSelection';
export * from './nestedAggregationResponse';
export * from './orderBySpec';
export * from './outputTransaction';
export * from './pagedResourceListOfPortfolioSearchResult';
export * from './pagedResourceListOfPropertyDefinition';
export * from './perpetualProperty';
export * from './portfolio';
export * from './portfolioDetails';
export * from './portfolioGroup';
export * from './portfolioHolding';
export * from './portfolioProperties';
export * from './portfolioReconciliationRequest';
export * from './portfolioSearchResult';
export * from './portfoliosReconciliationRequest';
export * from './pricingContext';
export * from './pricingOptions';
export * from './processedCommand';
export * from './property';
export * from './propertyDefinition';
export * from './propertyFilter';
export * from './propertySchema';
export * from './propertyValue';
export * from './quote';
export * from './quoteId';
export * from './quoteSeriesId';
export * from './realisedGainLoss';
export * from './reconciliationBreak';
export * from './referencePortfolioConstituent';
export * from './referencePortfolioConstituentRequest';
export * from './resourceId';
export * from './resourceListOfAccessControlledResource';
export * from './resourceListOfAnalyticStoreKey';
export * from './resourceListOfChange';
export * from './resourceListOfConstituentsAdjustmentHeader';
export * from './resourceListOfCorporateAction';
export * from './resourceListOfCorporateActionSource';
export * from './resourceListOfCutLabelDefinition';
export * from './resourceListOfDataType';
export * from './resourceListOfHoldingsAdjustmentHeader';
export * from './resourceListOfIUnitDefinitionDto';
export * from './resourceListOfInstrument';
export * from './resourceListOfInstrumentIdTypeDescriptor';
export * from './resourceListOfPortfolio';
export * from './resourceListOfPortfolioGroup';
export * from './resourceListOfPortfolioSearchResult';
export * from './resourceListOfProcessedCommand';
export * from './resourceListOfPropertyDefinition';
export * from './resourceListOfQuote';
export * from './resourceListOfReconciliationBreak';
export * from './resourceListOfScopeDefinition';
export * from './resourceListOfString';
export * from './resourceListOfTransactionConfigurationData';
export * from './resourceListOfValueType';
export * from './resultDataSchema';
export * from './results';
export * from './schema';
export * from './scopeDefinition';
export * from './stream';
export * from './structuredMarketData';
export * from './structuredMarketDataId';
export * from './targetTaxLot';
export * from './targetTaxLotRequest';
export * from './transaction';
export * from './transactionConfigurationData';
export * from './transactionConfigurationDataRequest';
export * from './transactionConfigurationMovementData';
export * from './transactionConfigurationMovementDataRequest';
export * from './transactionConfigurationTypeAlias';
export * from './transactionPrice';
export * from './transactionPropertyMapping';
export * from './transactionPropertyMappingRequest';
export * from './transactionQueryParameters';
export * from './transactionRequest';
export * from './updateCutLabelDefinitionRequest';
export * from './updateDataTypeRequest';
export * from './updateInstrumentIdentifierRequest';
export * from './updatePortfolioGroupRequest';
export * from './updatePortfolioRequest';
export * from './updatePropertyDefinitionRequest';
export * from './upsertCorporateActionRequest';
export * from './upsertCorporateActionsResponse';
export * from './upsertInstrumentPropertiesResponse';
export * from './upsertInstrumentPropertyRequest';
export * from './upsertInstrumentsResponse';
export * from './upsertPortfolioExecutionsResponse';
export * from './upsertPortfolioTransactionsResponse';
export * from './upsertQuoteRequest';
export * from './upsertQuotesResponse';
export * from './upsertReferencePortfolioConstituentsRequest';
export * from './upsertReferencePortfolioConstituentsResponse';
export * from './upsertStructuredDataResponse';
export * from './upsertStructuredMarketDataRequest';
export * from './upsertTransactionPropertiesResponse';
export * from './user';
export * from './valuationReconciliationRequest';
export * from './valuationsReconciliationRequest';
export * from './vendorModelRule';
export * from './version';
export * from './versionSummaryDto';
export * from './versionedResourceListOfOutputTransaction';
export * from './versionedResourceListOfPortfolioHolding';
export * from './versionedResourceListOfTransaction';
import localVarRequest = require('request');
export declare class ObjectSerializer {
    static findCorrectType(data: any, expectedType: string): any;
    static serialize(data: any, type: string): any;
    static deserialize(data: any, type: string): any;
}
export interface Authentication {
    /**
    * Apply authentication settings to header and query params.
    */
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class HttpBasicAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class ApiKeyAuth implements Authentication {
    private location;
    private paramName;
    apiKey: string;
    constructor(location: string, paramName: string);
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class OAuth implements Authentication {
    accessToken: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class VoidAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(_: localVarRequest.Options): void;
}
