/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CutLocalTime } from './cutLocalTime';

/**
* This request specifies a new Cut Label Definition
*/
export class CreateCutLabelDefinitionRequest {
    'code': string;
    'displayName': string;
    'description'?: string;
    'cutLocalTime': CutLocalTime;
    'timeZone': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "cutLocalTime",
            "baseName": "cutLocalTime",
            "type": "CutLocalTime"
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateCutLabelDefinitionRequest.attributeTypeMap;
    }
}

