/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CutLocalTime } from './cutLocalTime';
import { Link } from './link';

export class CutLabelDefinition {
    /**
    * 
    */
    'code'?: string;
    /**
    * 
    */
    'displayName'?: string;
    /**
    * 
    */
    'description'?: string;
    'cutLocalTime'?: CutLocalTime;
    /**
    * 
    */
    'timeZone'?: string;
    'href'?: string;
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "cutLocalTime",
            "baseName": "cutLocalTime",
            "type": "CutLocalTime"
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return CutLabelDefinition.attributeTypeMap;
    }
}

