/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1391
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ErrorDetail {
    /**
    * The id of the failed item that this error relates to.
    */
    'id'?: string;
    /**
    * The type of failure that occurred.
    */
    'type'?: string;
    /**
    * Description of the failure that occurred.
    */
    'detail'?: string;
    /**
    * Information about the particular instance of the failure (supplied information depends on the type of failure).
    */
    'errorDetails'?: Array<{ [key: string]: string; }>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string"
        },
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "Array<{ [key: string]: string; }>"
        }    ];

    static getAttributeTypeMap() {
        return ErrorDetail.attributeTypeMap;
    }
}

