/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1381
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Stream } from './stream';

/**
* Allows a file (represented as a stream) to be returned from an Api call
*/
export class FileResponse {
    'fileStream'?: Stream;
    'contentType'?: string;
    'downloadedFilename'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileStream",
            "baseName": "fileStream",
            "type": "Stream"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "downloadedFilename",
            "baseName": "downloadedFilename",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FileResponse.attributeTypeMap;
    }
}

