/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerpetualProperty } from './perpetualProperty';
import { TargetTaxLot } from './targetTaxLot';

/**
* The target holdings.
*/
export class HoldingAdjustment {
    /**
    * The set of instrument identifiers that can be used to resolve the holding adjustment to a unique instrument.
    */
    'instrumentIdentifiers'?: { [key: string]: string; };
    /**
    * The unqiue Lusid Instrument Id (LUID) of the instrument that the holding adjustment is in.
    */
    'instrumentUid': string;
    /**
    * The set of unique transaction properties and associated values stored with the holding adjustment transactions automatically created by LUSID. Each property will be from the \'Transaction\' domain.
    */
    'subHoldingKeys'?: { [key: string]: PerpetualProperty; };
    /**
    * The set of unique holding properties and associated values stored with the target holding. Each property will be from the \'Holding\' domain.
    */
    'properties'?: { [key: string]: PerpetualProperty; };
    /**
    * The tax-lots that together make up the target holding.
    */
    'taxLots': Array<TargetTaxLot>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "instrumentIdentifiers",
            "baseName": "instrumentIdentifiers",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "instrumentUid",
            "baseName": "instrumentUid",
            "type": "string"
        },
        {
            "name": "subHoldingKeys",
            "baseName": "subHoldingKeys",
            "type": "{ [key: string]: PerpetualProperty; }"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: PerpetualProperty; }"
        },
        {
            "name": "taxLots",
            "baseName": "taxLots",
            "type": "Array<TargetTaxLot>"
        }    ];

    static getAttributeTypeMap() {
        return HoldingAdjustment.attributeTypeMap;
    }
}

