/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1380
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The description of an allowable instrument identifier.
*/
export class InstrumentIdTypeDescriptor {
    /**
    * The name of the identifier type.
    */
    'identifierType': string;
    /**
    * The property key that corresponds to the identifier type.
    */
    'propertyKey': string;
    /**
    * Whether or not the identifier type is enforced to be unique.
    */
    'isUniqueIdentifierType': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "identifierType",
            "baseName": "identifierType",
            "type": "string"
        },
        {
            "name": "propertyKey",
            "baseName": "propertyKey",
            "type": "string"
        },
        {
            "name": "isUniqueIdentifierType",
            "baseName": "isUniqueIdentifierType",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InstrumentIdTypeDescriptor.attributeTypeMap;
    }
}

