/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1381
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PortfolioReconciliationRequest } from './portfolioReconciliationRequest';

export class PortfoliosReconciliationRequest {
    'left': PortfolioReconciliationRequest;
    'right': PortfolioReconciliationRequest;
    /**
    * Instrument properties to be included with any identified breaks. These properties will be in the effective and AsAt dates of the left portfolio
    */
    'instrumentPropertyKeys': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "left",
            "baseName": "left",
            "type": "PortfolioReconciliationRequest"
        },
        {
            "name": "right",
            "baseName": "right",
            "type": "PortfolioReconciliationRequest"
        },
        {
            "name": "instrumentPropertyKeys",
            "baseName": "instrumentPropertyKeys",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PortfoliosReconciliationRequest.attributeTypeMap;
    }
}

