/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1381
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyAndAmount } from './currencyAndAmount';

/**
* Used to specify holdings target amounts at the tax-lot level
*/
export class TargetTaxLot {
    /**
    * The number of units of the instrument in this tax-lot.
    */
    'units': number;
    'cost'?: CurrencyAndAmount;
    /**
    * The total cost of the tax-lot in the transaction portfolio\'s base currency.
    */
    'portfolioCost'?: number;
    /**
    * The purchase price of each unit of the instrument held in this tax-lot. This forms part of the unique key required for multiple tax-lots.
    */
    'price'?: number;
    /**
    * The purchase date of this tax-lot. This forms part of the unique key required for multiple tax-lots.
    */
    'purchaseDate'?: Date;
    /**
    * The settlement date of the tax-lot\'s opening transaction.
    */
    'settlementDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "units",
            "baseName": "units",
            "type": "number"
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "CurrencyAndAmount"
        },
        {
            "name": "portfolioCost",
            "baseName": "portfolioCost",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "purchaseDate",
            "baseName": "purchaseDate",
            "type": "Date"
        },
        {
            "name": "settlementDate",
            "baseName": "settlementDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TargetTaxLot.attributeTypeMap;
    }
}

