/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1387
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerpetualProperty } from './perpetualProperty';
import { TransactionConfigurationMovementDataRequest } from './transactionConfigurationMovementDataRequest';
import { TransactionConfigurationTypeAlias } from './transactionConfigurationTypeAlias';

export class TransactionConfigurationDataRequest {
    /**
    * List of transaction codes that map to this specific transaction model
    */
    'aliases': Array<TransactionConfigurationTypeAlias>;
    /**
    * Movement data for the transaction code
    */
    'movements': Array<TransactionConfigurationMovementDataRequest>;
    'properties'?: { [key: string]: PerpetualProperty; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Array<TransactionConfigurationTypeAlias>"
        },
        {
            "name": "movements",
            "baseName": "movements",
            "type": "Array<TransactionConfigurationMovementDataRequest>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: PerpetualProperty; }"
        }    ];

    static getAttributeTypeMap() {
        return TransactionConfigurationDataRequest.attributeTypeMap;
    }
}

