/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1380
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from './link';
import { SideConfigurationData } from './sideConfigurationData';
import { TransactionConfigurationData } from './transactionConfigurationData';

/**
* A collection of the data required to configure transaction types..
*/
export class TransactionSetConfigurationData {
    /**
    * Collection of transaction type models
    */
    'transactionConfigs': Array<TransactionConfigurationData>;
    /**
    * Collection of side definitions
    */
    'sideDefinitions'?: Array<SideConfigurationData>;
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionConfigs",
            "baseName": "transactionConfigs",
            "type": "Array<TransactionConfigurationData>"
        },
        {
            "name": "sideDefinitions",
            "baseName": "sideDefinitions",
            "type": "Array<SideConfigurationData>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return TransactionSetConfigurationData.attributeTypeMap;
    }
}

