/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1388
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerpetualProperty } from './perpetualProperty';
import { TransactionConfigurationMovementData } from './transactionConfigurationMovementData';
import { TransactionConfigurationTypeAlias } from './transactionConfigurationTypeAlias';

export class TransactionConfigurationData {
    /**
    * List of transaction codes that map to this specific transaction model
    */
    'aliases': Array<TransactionConfigurationTypeAlias>;
    /**
    * Movement data for the transaction code
    */
    'movements': Array<TransactionConfigurationMovementData>;
    'properties'?: { [key: string]: PerpetualProperty; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Array<TransactionConfigurationTypeAlias>"
        },
        {
            "name": "movements",
            "baseName": "movements",
            "type": "Array<TransactionConfigurationMovementData>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: PerpetualProperty; }"
        }    ];

    static getAttributeTypeMap() {
        return TransactionConfigurationData.attributeTypeMap;
    }
}

