/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1383
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorDetail } from './errorDetail';
import { Instrument } from './instrument';
import { Link } from './link';

export class UpsertInstrumentsResponse {
    /**
    * The specific Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.
    */
    'href'?: string;
    /**
    * The instruments which have been successfully updated or inserted.
    */
    'values'?: { [key: string]: Instrument; };
    /**
    * The instruments that could not be updated or inserted along with a reason for their failure.
    */
    'failed'?: { [key: string]: ErrorDetail; };
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "{ [key: string]: Instrument; }"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "{ [key: string]: ErrorDetail; }"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return UpsertInstrumentsResponse.attributeTypeMap;
    }
}

