export * from './addressKeyDefinitionApi';
import { AddressKeyDefinitionApi } from './addressKeyDefinitionApi';
export * from './aggregationApi';
import { AggregationApi } from './aggregationApi';
export * from './allocationsApi';
import { AllocationsApi } from './allocationsApi';
export * from './applicationMetadataApi';
import { ApplicationMetadataApi } from './applicationMetadataApi';
export * from './blocksApi';
import { BlocksApi } from './blocksApi';
export * from './calendarsApi';
import { CalendarsApi } from './calendarsApi';
export * from './complexMarketDataApi';
import { ComplexMarketDataApi } from './complexMarketDataApi';
export * from './complianceGenericApi';
import { ComplianceGenericApi } from './complianceGenericApi';
export * from './configurationRecipeApi';
import { ConfigurationRecipeApi } from './configurationRecipeApi';
export * from './corporateActionSourcesApi';
import { CorporateActionSourcesApi } from './corporateActionSourcesApi';
export * from './counterpartiesApi';
import { CounterpartiesApi } from './counterpartiesApi';
export * from './customEntitiesApi';
import { CustomEntitiesApi } from './customEntitiesApi';
export * from './customEntityDefinitionsApi';
import { CustomEntityDefinitionsApi } from './customEntityDefinitionsApi';
export * from './cutLabelDefinitionsApi';
import { CutLabelDefinitionsApi } from './cutLabelDefinitionsApi';
export * from './dataTypesApi';
import { DataTypesApi } from './dataTypesApi';
export * from './derivedTransactionPortfoliosApi';
import { DerivedTransactionPortfoliosApi } from './derivedTransactionPortfoliosApi';
export * from './entitiesApi';
import { EntitiesApi } from './entitiesApi';
export * from './executionsApi';
import { ExecutionsApi } from './executionsApi';
export * from './instrumentsApi';
import { InstrumentsApi } from './instrumentsApi';
export * from './legalEntitiesApi';
import { LegalEntitiesApi } from './legalEntitiesApi';
export * from './ordersApi';
import { OrdersApi } from './ordersApi';
export * from './participationsApi';
import { ParticipationsApi } from './participationsApi';
export * from './personsApi';
import { PersonsApi } from './personsApi';
export * from './placementsApi';
import { PlacementsApi } from './placementsApi';
export * from './portfolioGroupsApi';
import { PortfolioGroupsApi } from './portfolioGroupsApi';
export * from './portfoliosApi';
import { PortfoliosApi } from './portfoliosApi';
export * from './propertyDefinitionsApi';
import { PropertyDefinitionsApi } from './propertyDefinitionsApi';
export * from './quotesApi';
import { QuotesApi } from './quotesApi';
export * from './reconciliationsApi';
import { ReconciliationsApi } from './reconciliationsApi';
export * from './referenceListsApi';
import { ReferenceListsApi } from './referenceListsApi';
export * from './referencePortfolioApi';
import { ReferencePortfolioApi } from './referencePortfolioApi';
export * from './relationshipDefinitionsApi';
import { RelationshipDefinitionsApi } from './relationshipDefinitionsApi';
export * from './relationshipsApi';
import { RelationshipsApi } from './relationshipsApi';
export * from './schemasApi';
import { SchemasApi } from './schemasApi';
export * from './scopesApi';
import { ScopesApi } from './scopesApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './sequencesApi';
import { SequencesApi } from './sequencesApi';
export * from './structuredResultDataApi';
import { StructuredResultDataApi } from './structuredResultDataApi';
export * from './systemConfigurationApi';
import { SystemConfigurationApi } from './systemConfigurationApi';
export * from './transactionPortfoliosApi';
import { TransactionPortfoliosApi } from './transactionPortfoliosApi';

export { RequestFile } from '../model/models';

export const APIS = [AddressKeyDefinitionApi, AggregationApi, AllocationsApi, ApplicationMetadataApi, BlocksApi, CalendarsApi, ComplexMarketDataApi, ComplianceGenericApi, ConfigurationRecipeApi, CorporateActionSourcesApi, CounterpartiesApi, CustomEntitiesApi, CustomEntityDefinitionsApi, CutLabelDefinitionsApi, DataTypesApi, DerivedTransactionPortfoliosApi, EntitiesApi, ExecutionsApi, InstrumentsApi, LegalEntitiesApi, OrdersApi, ParticipationsApi, PersonsApi, PlacementsApi, PortfolioGroupsApi, PortfoliosApi, PropertyDefinitionsApi, QuotesApi, ReconciliationsApi, ReferenceListsApi, ReferencePortfolioApi, RelationshipDefinitionsApi, RelationshipsApi, SchemasApi, ScopesApi, SearchApi, SequencesApi, StructuredResultDataApi, SystemConfigurationApi, TransactionPortfoliosApi];
