export * from './aggregationApi';
import { AggregationApi } from './aggregationApi';
export * from './analyticsStoresApi';
import { AnalyticsStoresApi } from './analyticsStoresApi';
export * from './applicationMetadataApi';
import { ApplicationMetadataApi } from './applicationMetadataApi';
export * from './corporateActionSourcesApi';
import { CorporateActionSourcesApi } from './corporateActionSourcesApi';
export * from './cutLabelDefinitionsApi';
import { CutLabelDefinitionsApi } from './cutLabelDefinitionsApi';
export * from './dataTypesApi';
import { DataTypesApi } from './dataTypesApi';
export * from './derivedTransactionPortfoliosApi';
import { DerivedTransactionPortfoliosApi } from './derivedTransactionPortfoliosApi';
export * from './entitiesApi';
import { EntitiesApi } from './entitiesApi';
export * from './instrumentsApi';
import { InstrumentsApi } from './instrumentsApi';
export * from './loginApi';
import { LoginApi } from './loginApi';
export * from './portfolioGroupsApi';
import { PortfolioGroupsApi } from './portfolioGroupsApi';
export * from './portfoliosApi';
import { PortfoliosApi } from './portfoliosApi';
export * from './propertyDefinitionsApi';
import { PropertyDefinitionsApi } from './propertyDefinitionsApi';
export * from './quotesApi';
import { QuotesApi } from './quotesApi';
export * from './reconciliationsApi';
import { ReconciliationsApi } from './reconciliationsApi';
export * from './referencePortfolioApi';
import { ReferencePortfolioApi } from './referencePortfolioApi';
export * from './resultsApi';
import { ResultsApi } from './resultsApi';
export * from './schemasApi';
import { SchemasApi } from './schemasApi';
export * from './scopesApi';
import { ScopesApi } from './scopesApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './structuredMarketDataApi';
import { StructuredMarketDataApi } from './structuredMarketDataApi';
export * from './systemConfigurationApi';
import { SystemConfigurationApi } from './systemConfigurationApi';
export * from './transactionPortfoliosApi';
import { TransactionPortfoliosApi } from './transactionPortfoliosApi';
export const APIS = [AggregationApi, AnalyticsStoresApi, ApplicationMetadataApi, CorporateActionSourcesApi, CutLabelDefinitionsApi, DataTypesApi, DerivedTransactionPortfoliosApi, EntitiesApi, InstrumentsApi, LoginApi, PortfolioGroupsApi, PortfoliosApi, PropertyDefinitionsApi, QuotesApi, ReconciliationsApi, ReferencePortfolioApi, ResultsApi, SchemasApi, ScopesApi, SearchApi, StructuredMarketDataApi, SystemConfigurationApi, TransactionPortfoliosApi];
