"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./applicationMetadataApi"));
var applicationMetadataApi_1 = require("./applicationMetadataApi");
__export(require("./cutLabelDefinitionsApi"));
var cutLabelDefinitionsApi_1 = require("./cutLabelDefinitionsApi");
__export(require("./dataTypesApi"));
var dataTypesApi_1 = require("./dataTypesApi");
__export(require("./derivedTransactionPortfoliosApi"));
var derivedTransactionPortfoliosApi_1 = require("./derivedTransactionPortfoliosApi");
__export(require("./instrumentsApi"));
var instrumentsApi_1 = require("./instrumentsApi");
__export(require("./loginApi"));
var loginApi_1 = require("./loginApi");
__export(require("./portfolioGroupsApi"));
var portfolioGroupsApi_1 = require("./portfolioGroupsApi");
__export(require("./portfoliosApi"));
var portfoliosApi_1 = require("./portfoliosApi");
__export(require("./propertyDefinitionsApi"));
var propertyDefinitionsApi_1 = require("./propertyDefinitionsApi");
__export(require("./reconciliationsApi"));
var reconciliationsApi_1 = require("./reconciliationsApi");
__export(require("./referencePortfolioApi"));
var referencePortfolioApi_1 = require("./referencePortfolioApi");
__export(require("./scopesApi"));
var scopesApi_1 = require("./scopesApi");
__export(require("./systemConfigurationApi"));
var systemConfigurationApi_1 = require("./systemConfigurationApi");
__export(require("./transactionPortfoliosApi"));
var transactionPortfoliosApi_1 = require("./transactionPortfoliosApi");
exports.APIS = [applicationMetadataApi_1.ApplicationMetadataApi, cutLabelDefinitionsApi_1.CutLabelDefinitionsApi, dataTypesApi_1.DataTypesApi, derivedTransactionPortfoliosApi_1.DerivedTransactionPortfoliosApi, instrumentsApi_1.InstrumentsApi, loginApi_1.LoginApi, portfolioGroupsApi_1.PortfolioGroupsApi, portfoliosApi_1.PortfoliosApi, propertyDefinitionsApi_1.PropertyDefinitionsApi, reconciliationsApi_1.ReconciliationsApi, referencePortfolioApi_1.ReferencePortfolioApi, scopesApi_1.ScopesApi, systemConfigurationApi_1.SystemConfigurationApi, transactionPortfoliosApi_1.TransactionPortfoliosApi];
