"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./aggregationApi"));
var aggregationApi_1 = require("./aggregationApi");
__export(require("./analyticsStoresApi"));
var analyticsStoresApi_1 = require("./analyticsStoresApi");
__export(require("./applicationMetadataApi"));
var applicationMetadataApi_1 = require("./applicationMetadataApi");
__export(require("./corporateActionSourcesApi"));
var corporateActionSourcesApi_1 = require("./corporateActionSourcesApi");
__export(require("./cutLabelDefinitionsApi"));
var cutLabelDefinitionsApi_1 = require("./cutLabelDefinitionsApi");
__export(require("./dataTypesApi"));
var dataTypesApi_1 = require("./dataTypesApi");
__export(require("./derivedTransactionPortfoliosApi"));
var derivedTransactionPortfoliosApi_1 = require("./derivedTransactionPortfoliosApi");
__export(require("./entitiesApi"));
var entitiesApi_1 = require("./entitiesApi");
__export(require("./instrumentsApi"));
var instrumentsApi_1 = require("./instrumentsApi");
__export(require("./loginApi"));
var loginApi_1 = require("./loginApi");
__export(require("./portfolioGroupsApi"));
var portfolioGroupsApi_1 = require("./portfolioGroupsApi");
__export(require("./portfoliosApi"));
var portfoliosApi_1 = require("./portfoliosApi");
__export(require("./propertyDefinitionsApi"));
var propertyDefinitionsApi_1 = require("./propertyDefinitionsApi");
__export(require("./quotesApi"));
var quotesApi_1 = require("./quotesApi");
__export(require("./reconciliationsApi"));
var reconciliationsApi_1 = require("./reconciliationsApi");
__export(require("./referencePortfolioApi"));
var referencePortfolioApi_1 = require("./referencePortfolioApi");
__export(require("./resultsApi"));
var resultsApi_1 = require("./resultsApi");
__export(require("./schemasApi"));
var schemasApi_1 = require("./schemasApi");
__export(require("./scopesApi"));
var scopesApi_1 = require("./scopesApi");
__export(require("./searchApi"));
var searchApi_1 = require("./searchApi");
__export(require("./structuredMarketDataApi"));
var structuredMarketDataApi_1 = require("./structuredMarketDataApi");
__export(require("./systemConfigurationApi"));
var systemConfigurationApi_1 = require("./systemConfigurationApi");
__export(require("./transactionPortfoliosApi"));
var transactionPortfoliosApi_1 = require("./transactionPortfoliosApi");
exports.APIS = [aggregationApi_1.AggregationApi, analyticsStoresApi_1.AnalyticsStoresApi, applicationMetadataApi_1.ApplicationMetadataApi, corporateActionSourcesApi_1.CorporateActionSourcesApi, cutLabelDefinitionsApi_1.CutLabelDefinitionsApi, dataTypesApi_1.DataTypesApi, derivedTransactionPortfoliosApi_1.DerivedTransactionPortfoliosApi, entitiesApi_1.EntitiesApi, instrumentsApi_1.InstrumentsApi, loginApi_1.LoginApi, portfolioGroupsApi_1.PortfolioGroupsApi, portfoliosApi_1.PortfoliosApi, propertyDefinitionsApi_1.PropertyDefinitionsApi, quotesApi_1.QuotesApi, reconciliationsApi_1.ReconciliationsApi, referencePortfolioApi_1.ReferencePortfolioApi, resultsApi_1.ResultsApi, schemasApi_1.SchemasApi, scopesApi_1.ScopesApi, searchApi_1.SearchApi, structuredMarketDataApi_1.StructuredMarketDataApi, systemConfigurationApi_1.SystemConfigurationApi, transactionPortfoliosApi_1.TransactionPortfoliosApi];
